export const NAME_POOL = {
  first: {
    A: ["Aaron","Abel","Abraham","Ace","Adam","Aden","Adrian","Aiden","Alan","Albert","Alec","Alex","Alfred","Alvin","Ambrose","Amos","Andrew","Angus","Ansel","Anthony","Apollo","Archer","Arlo","Arnold","Arthur","Asher","Atlas","Atticus","August","Austin","Axel","Ayden"],
    B: ["Barrett","Bastian","Beckett","Benjamin","Bennett","Bentley","Blake","Bo","Boden","Brady","Bram","Brandon","Brantley","Brennan","Brett","Brian","Brice","Brock","Brooks","Bruno","Bryan","Bryson","Burke","Byron"],
    C: ["Caden","Caiden","Caleb","Calvin","Camden","Cameron","Carl","Carson","Carter","Cash","Casper","Caspian","Cecil","Cedar","Charles","Chase","Chester","Christian","Christopher","Clark","Clay","Clayton","Clement","Cody","Cole","Colin","Connor","Cooper","Corey","Crew","Cruz","Curtis"],
    D: ["Dacian","Dakota","Damian","Dane","Daniel","Dante","Darian","Darius","Davis","Dawson","Declan","Derek","Desmond","Devin","Devon","Donovan","Drake","Drew","Duke","Duncan","Dylan"],
    E: ["Earl","Easton","Edward","Eli","Elias","Elijah","Elliott","Ellis","Emerson","Emil","Emmett","Eric","Ethan","Evan","Everett","Ezekiel","Ezra"],
    F: ["Felix","Finley","Finn","Fletcher","Flynn","Ford","Fox","Francis","Frank","Franklin","Frederick"],
    G: ["Gage","Garrett","George","Graham","Grant","Gray","Grayson","Gregory","Griffin","Gunner","Gunnar","Gus"],
    H: ["Hank","Harlan","Harley","Harrison","Harvey","Hayes","Henry","Hugh","Hugo","Hunter"],
    I: ["Ian","Idris","Isaac","Isaiah","Ivan"],
    J: ["Jack","Jackson","Jacob","James","Jasper","Jaxon","Jace","Jaden","Jake","Jared","Jason","Jay","Jedidiah","Jesse","Joel","John","Jonas","Jonathan","Jordan","Joseph","Josh","Joshua","Jude","Julian","Julien","Julius","Justin"],
    K: ["Kai","Kaleb","Kane","Keaton","Kellan","Kendall","Kennedy","Kenneth","Kevin","Knox"],
    L: ["Lance","Landon","Lane","Levi","Lewis","Liam","Lincoln","Logan","Luca","Lucas","Luke","Lyle","Lyndon"],
    M: ["Mason","Maverick","Miles","Milo","Max","Marcus","Mateo","Matthew","Michael","Morgan","Montgomery","Maxwell","Malcolm","Marshall","Micah","Mitchell","Monroe","Morris","Moses","Murphy","Magnus","Mercer","Marlowe","Moss","Monty","Mace","Maddox","Malik","Manuel","Mario","Martin","Maurice","Maxton","Merritt","Miro","Myles"],
    N: ["Nathan","Nathaniel","Neil","Nelson","Nicholas","Nico","Noah","Noel","Nolan","Norman"],
    O: ["Oak","Oliver","Omari","Orion","Orlando","Oscar","Otis","Otto","Owen"],
    P: ["Parker","Patrick","Paul","Penn","Percy","Peter","Philip","Phoenix","Pierce","Preston"],
    Q: ["Quentin","Quinn"],
    R: ["Rafael","Raymond","Reed","Reid","Rhett","Richard","Riordan","River","Robert","Robin","Roman","Ronan","Ross","Rowan","Ryder"],
    S: ["Sam","Samuel","Sawyer","Sebastian","Seth","Shane","Simon","Silas","Slate","Solomon","Spencer","Sterling","Steven","Sullivan"],
    T: ["Tate","Theodore","Thomas","Timothy","Tobias","Toby","Travis","Trent","Tristan","Tucker","Tyler"],
    U: ["Ulric","Ulysses","Uri"],
    V: ["Vance","Victor","Vincent","Virgil"],
    W: ["Wade","Walker","Walter","Warren","Wesley","Wilder","William","Willis","Winston","Wyatt"],
    X: ["Xavier","Xander"],
    Y: ["Yale","Yusuf"],
    Z: ["Zach","Zachary","Zane","Zeb","Zeke","Zion"],
  },
  middle: {
    A: ["Aaron","Abel","Adam","Alan","Albert","Alexander","Alfred","Allan","Allen","Alton","Alvin","Ambrose","Andrew","Anthony","Arnold","Arthur","Asher","August","Austin"],
    B: ["Barrett","Benjamin","Bennett","Blake","Bradley","Brandon","Brian","Brooks","Bruce","Bryan"],
    C: ["Calvin","Cameron","Carl","Charles","Chester","Christian","Christopher","Clark","Clayton","Clement","Cole","Colton","Curtis"],
    D: ["Dale","Daniel","David","Dean","Dennis","Derek","Dominic","Donald","Douglas","Duane","Duke","Duncan"],
    E: ["Earl","Edmund","Edward","Edwin","Eli","Elias","Elijah","Elliot","Elliott","Emmett","Eric","Eugene","Evan","Everett"],
    F: ["Felix","Francis","Frank","Franklin","Frederick"],
    G: ["Gabriel","George","Gerald","Gordon","Graham","Grant","Gregory"],
    H: ["Harold","Harrison","Harvey","Henry","Herbert","Howard","Hugh"],
    I: ["Ian","Irving","Isaac","Isaiah","Ivan"],
    J: ["Jack","Jacob","James","Jasper","Jay","John","Jonas","Jonathan","Joseph","Joshua","Julian","Julius","Justin"],
    K: ["Keith","Kenneth","Kevin","Kirk"],
    L: ["Lance","Lawrence","Lee","Leonard","Levi","Lewis","Lloyd","Logan","Louis","Lucas","Luke"],
    M: ["Mark","Martin","Maurice","Michael","Mitchell","Monroe","Montgomery"],
    N: ["Nathan","Nathaniel","Neil","Nicholas","Noel","Norman"],
    O: ["Oliver","Orion","Oscar","Otto","Owen"],
    P: ["Patrick","Paul","Peter","Philip","Preston"],
    Q: ["Quentin"],
    R: ["Ralph","Raymond","Reed","Richard","Robert","Roger","Roland","Ronald","Ross","Roy","Russell"],
    S: ["Samuel","Scott","Sebastian","Silas","Simon","Stanley","Stephen","Steven"],
    T: ["Theodore","Thomas","Timothy","Tobias","Travis","Trent","Tucker"],
    U: ["Ulric","Ulysses"],
    V: ["Victor","Vincent","Virgil"],
    W: ["Walter","Warren","Wayne","Wesley","William","Willis","Winston"],
    X: ["Xavier"],
    Y: ["Yusuf"],
    Z: ["Zachary","Zebediah","Zeke"],
  },
}

export const ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZ".split("")
